// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aapzocqocxneqxxcylyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcHpvY3FvY3huZXF4eGN5bHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTg2MzMsImV4cCI6MjA1OTM3NDYzM30.MEglM4ql_gJP_-NRZ0KiuE0kn736KgrPN7wIuODpe_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);